import { IPage } from "./IPage";
import { IVirtualAccountAdmin } from "./IVirtualAccountAdmin";

/**
 * 관리자 계정 리스트의 페이징 결과 DTO. admin 리스트화면, 검색 등.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountAdmin = {
  pagination: IPage.IPagination;
  data: IVirtualAccountAdmin[];
};
