import { IPage } from "./IPage";
import { IVirtualAccountNotificationChannel } from "./IVirtualAccountNotificationChannel";

/**
 * 알림 채널 목록의 표준 페이징 응답 타입.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountNotificationChannel = {
  pagination?: IPage.IPagination;
  data?: IVirtualAccountNotificationChannel[];
};
