import { IPage } from "./IPage";
import { IVirtualAccountAuditLog } from "./IVirtualAccountAuditLog";

/**
 * 감사로그(virtual_account_audit_logs) 리스트 표준 페이징 응답 구조.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountAuditLog = {
  pagination: IPage.IPagination;
  data: IVirtualAccountAuditLog[];
};
