import { IPage } from "./IPage";
import { IVirtualAccountCustomer } from "./IVirtualAccountCustomer";

/**
 * 고객 리스트 조회 시 페이징 결과 래퍼. pagination(페이지정보), data(고객 배열)로 구성되며, 대시보드, 검색 화면 등에서
 * 사용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountCustomer = {
  pagination: IPage.IPagination;

  /** 페이지별 고객 요약 정보 배열. 각 원소는 IVirtualAccountCustomer 타입. */
  data: IVirtualAccountCustomer[];
};
