import { IPage } from "./IPage";
import { virtual_account_materialized_stats } from "./virtual_account_materialized_stats";

/**
 * 대시보드 집계 지표(virtual_account_materialized_stats) 리스트의 페이지네이션 래퍼 타입입니다. 표준 IPage
 * 구조를 준수하며, 대량 데이터 처리/다운로드/리포트/통계 관리에 효율적으로 사용 가능합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountMaterializedStats = {
  pagination?: IPage.IPagination;

  /** 현재 페이지를 구성하는 대시보드 집계 스냅샷 엔터티 배열. */
  data?: virtual_account_materialized_stats[];
};
