import { IPage } from "./IPage";
import { IVirtualAccountErpTypes } from "./IVirtualAccountErpTypes";

/**
 * ERP 타입 목록의 페이지네이션 결과 컨테이너입니다.
 *
 * 관리자 대시보드, 시스템 연결설정 화면 등에서 ERP타입 테이블의 페이징/검색/다운로드 용도로 반환됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountErpTypes = {
  pagination: IPage.IPagination;

  /** ERP 타입 리스트. */
  data: IVirtualAccountErpTypes[];
};
