import { IPage } from "./IPage";
import { IVirtualAccountDashboardSettings } from "./IVirtualAccountDashboardSettings";

/**
 * 관리자 대시보드 환경설정 목록 페이지네이션 응답 타입.
 *
 * `virtual_account_dashboard_settings` 테이블의 여러 행(레코드)을 조건 및 페이징에 따라 반환하는 표준
 * 포맷입니다. 페이지네이션 정보와 대시보드 설정 리스트를 함께 제공합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountDashboardSettings = {
  /**
   * 페이지네이션 정보.
   *
   * 현재 페이지, 페이지당 제한, 데이터 전체 개수 및 전체 페이지 수가 포함됩니다. 이 정보는 관리자 대시보드 설정 목록 요청에 대한
   * 응답의 메타데이터로 활용됩니다.
   */
  pagination: IPage.IPagination;

  /**
   * 대시보드 설정 레코드 목록.
   *
   * 각 항목은 개별 관리자의 대시보드 환경설정 정보를 담고 있습니다.
   */
  data: IVirtualAccountDashboardSettings[];
};
