import { IPage } from "./IPage";
import { IVirtualAccountDepositMatchings } from "./IVirtualAccountDepositMatchings";

/**
 * 가상계좌 입금 매칭 기록의 페이징된 결과입니다.
 *
 * 이 객체는 관리자 대시보드에서 제공되는 입금 매칭 조회 기능에서 사용됩니다. pagination에는 현재 페이지, 한 페이지의 레코드 수,
 * 전체 데이터 개수 등이 포함되며, data에는 매칭 레코드의 배열이 들어갑니다.
 *
 * 각 매칭 레코드는 단일 입금에 대한 자동 또는 수동 매칭 수행 이력을 담고 있습니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountDepositMatchings = {
  /** 페이지네이션 정보입니다. 쿼리 결과의 현재 페이지, 한 페이지의 최대 결과 수, 전체 레코드 수 등의 정보를 포함합니다. */
  pagination: IPage.IPagination;

  /** 조회된 가상계좌 입금 매칭 기록 객체 배열입니다. */
  data: IVirtualAccountDepositMatchings[];
};
