import { IPage } from "./IPage";
import { IVirtualAccountExternalIntegrationLogs } from "./IVirtualAccountExternalIntegrationLogs";

/**
 * 외부 연동 이벤트 로그 검색 결과(페이징)
 *
 * Virtual_account_external_integration_logs 테이블에서 조건검색시 페이지네이션 출력용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountExternalIntegrationLogs = {
  pagination: IPage.IPagination;
  data: IVirtualAccountExternalIntegrationLogs[];
};
