import { IPage } from "./IPage";
import { IVirtualAccountVirtualAccount } from "./IVirtualAccountVirtualAccount";

/**
 * 가상계좌 페이징 리스트 응답. 대시보드 등에서 사용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountVirtualAccount = {
  pagination: IPage.IPagination;
  data: IVirtualAccountVirtualAccount[];
};
