import { IPage } from "./IPage";
import { IVirtualAccountNotificationEventLog } from "./IVirtualAccountNotificationEventLog";

/**
 * 알림 이벤트 로그 목록 페이지 DTO.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountNotificationEventLog = {
  pagination: IPage.IPagination;
  data: IVirtualAccountNotificationEventLog[];
};
