import { IPage } from "./IPage";
import { IVirtualAccountAdminAlerts } from "./IVirtualAccountAdminAlerts";

/**
 * 관리자 경보(알림) 페이징 목록 응답 구성체.
 *
 * Virtual_account_admin_alerts 테이블을 기반으로, 관리자 대시보드의 경보/알림 이력 표, 이상 패턴 감지 이벤트,
 * 외부 연동 장애/오류 알림 등에 활용됩니다.
 *
 * 각 페이지네이션 정보와 개별 알림 배열로 구성되어 있으며, 시스템에서 발생한 주요 이벤트, 위험 상황, 관리자 대상 공지 등을 제공합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountAdminAlerts = {
  /** 페이지네이션 및 전체 카운트 정보. 대시보드 UI의 페이징, 총 경보 갯수 표시, 내보내기 등에 반드시 사용됩니다. */
  pagination: IPage.IPagination;

  /**
   * 관리자 경보/알림 엔티티 리스트. 한 페이지 내 최대 N건. 각 알림은 상세 설명, 발생 시각, 관련 관리자 등 모든 주요 정보를
   * 담고 있습니다.
   */
  data: IVirtualAccountAdminAlerts[];
};
