import { IPage } from "./IPage";
import { IVirtualAccountOAuthClients } from "./IVirtualAccountOAuthClients";

/**
 * OAuth Client 목록 페이징 결과(응답) 구조체입니다.
 *
 * Pagination에는 페이지 번호·총 개수·한 페이지당 레코드 수가 담기고, data에는 OAuth client 메타 정보 배열이
 * 포함됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountOAuthClients = {
  pagination: IPage.IPagination;

  /** OAuth Client에 대한 목록 배열로, 각 아이템은 상세 타입을 따릅니다. */
  data: IVirtualAccountOAuthClients[];
};
