import { IPage } from "./IPage";
import { IVirtualAccountDeposits } from "./IVirtualAccountDeposits";

/**
 * 입금내역 페이징/검색 결과용 공통 컨테이너입니다.
 *
 * 페이지네이션 메타+결과 리스트(IVirtualAccountDeposits)로 구성하며, 대시보드·API 공통 포맷을 따릅니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountDeposits = {
  pagination: IPage.IPagination;

  /**
   * 현재 페이지 결과 데이터 배열.
   *
   * IVirtualAccountDeposits 스키마(입금내역 상세) 기준.
   */
  data: IVirtualAccountDeposits[];
};
