import { IPage } from "./IPage";
import { virtual_account_admin_activity_logs } from "./virtual_account_admin_activity_logs";

/**
 * 관리자 행위/감사 로그 페이징 결과 오브젝트
 *
 * Virtual_account_admin_activity_logs(PK 기준으로 페이지별/조건별 조회시 최종 결과. 대시보드,
 * Excel내보내기, 검색 뷰에서 사용)
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPagevirtual_account_admin_activity_logs = {
  /** 페이징 정보. 전체 레코드 수, 현재 페이지 등 */
  pagination: IPage.IPagination;

  /** 감사 로그 단건 목록. virtual_account_admin_activity_logs 오브젝트 배열 */
  data: virtual_account_admin_activity_logs[];
};
