import { IPage } from "./IPage";
import { IVirtualAccountRole } from "./IVirtualAccountRole";

/**
 * 역할(RBAC Role) 목록의 페이징 결과 오브젝트. IPage<T> 패턴을 따르며, pagination(페이징정보) 및 data(역할
 * 목록 배열)로 구성됩니다.
 *
 * 실제 조회시 페이지별 데이터와 전체/총건수 및 페이지 정보가 함께 리턴됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountRole = {
  pagination: IPage.IPagination;

  /** 현 페이지의 역할 목록 */
  data: IVirtualAccountRole[];
};
