import { IPage } from "./IPage";
import { IVirtualAccountExcelExports } from "./IVirtualAccountExcelExports";

/**
 * 엑셀 다운로드(내보내기) 이력 리스트 응답 타입.
 *
 * `virtual_account_excel_exports` 테이블 데이터의 페이지 단위 목록을 페이징 및 메타데이터와 함께 제공합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIVirtualAccountExcelExports = {
  /**
   * 페이지네이션 정보.
   *
   * 다운로드 이력 목록의 전체 개수, 현재 페이지, 페이지당 최대 개수 등 메타데이터 포함.
   */
  pagination: IPage.IPagination;

  /**
   * 엑셀 다운로드 이력 레코드 배열.
   *
   * 각 레코드에는 관리자, 필터, 파일 위치, 성공여부 등 메타 정보가 포함됩니다.
   */
  data: IVirtualAccountExcelExports[];
};
