import { tags } from "typia";

/**
 * 알림 채널(카카오/메일/SMS 등) 정보 단건. 채널 특성, 활성화 상태, 채널 별 설정JSON 등 포함.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountNotificationChannel = {
  id?: string & tags.Format<"uuid">;
  channel_type?: string;
  display_name?: string;
  is_active?: boolean;
  settings_json?: string;
};
export namespace IVirtualAccountNotificationChannel {
  /** 알림 채널(카카오,메일,SMS 등) 리스트/검색/페이징요청 DTO. */
  export type IRequest = {
    channel_type?: string;
    display_name?: string;
    is_active?: boolean;
  };

  /** 알림 채널(카카오톡, 이메일 등) 신규 생성용 DTO. 채널특성, 설정 값 포함. */
  export type ICreate = {
    channel_type: string;
    display_name: string;
    is_active: boolean;
    settings_json: string;
  };

  /** 알림 채널 일부 속성 패치/수정용 DTO. channel_type(구분)는 immutable. */
  export type IUpdate = {
    display_name?: string;
    is_active?: boolean;
    settings_json?: string;
  };
}
