import { tags } from "typia";

/**
 * 단일 ERP 타입(벤더코드) 행 정보 구조(조회 등 단건뷰 응답).
 *
 * Prisma 엔티티 구조/주석 기반 ERP 통합관리/검색용 활용 케이스에 직결.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountErpType = {
  /** ERP 타입 고유 식별자(Prisma의 id FK 및 조회키). */
  id: string & tags.Format<"uuid">;

  /** ERP 코드값(벤더 구분). Prisma 코드 컬럼 참조. */
  code: string;

  /** ERP 한글 표기. 관리자 UI, 통합 연동제어 등에서 활용. */
  display_name: string;

  /** 등록 일시(ISO8601). Prisma 생성일 컬럼과 동일. */
  created_at: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountErpType {
  /**
   * ERP 타입(벤더) 정보 수정시의 요청 바디 타입입니다.
   *
   * 변경가능 필드를 명확히 표기합니다.
   */
  export type IUpdate = {
    /**
     * ERP 타입의 표기명(수정용). Prisma description 참고.
     *
     * 관리자 라이프사이클에서 ERP 벤더명 대체, UI 변경 등에 활용됩니다.
     */
    display_name?: string;
  };

  /**
   * ERP 타입 삭제(취소) 요청에 대한 결과 데이터 구조.
   *
   * 최종 삭제 성공, 실패 및 대상 식별자를 반환합니다.
   */
  export type IDeleteResult = {
    /**
     * 삭제한 ERP 타입 식별자.
     *
     * Prisma 고유키 설명과 동일.
     */
    id: string & tags.Format<"uuid">;

    /**
     * 삭제 여부(성공=TRUE, 실패=FALSE).
     *
     * 삭제결과를 출력합니다.
     */
    deleted: boolean;
  };
}
