import { tags } from "typia";

/**
 * PG사 마스터 엔터티. 명칭,코드,API엔드 포인트 등 연동용 속성. 발급/연동 마스터 관리에 사용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountPgProvider = {
  id: string & tags.Format<"uuid">;

  /** PG사 명칭. */
  name: string;

  /** PG코드. */
  code: string;

  /** API 엔드포인트(URL). */
  api_endpoint: string;
  created_at: string & tags.Format<"date-time">;
  updated_at: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountPgProvider {
  /** 가상계좌 PG 시스템 (KG, TOSS 등) 리스트/검색/페이징 요청 DTO. */
  export type IRequest = {
    /** PG사명(검색). */
    name?: string;

    /** PG코드(필터). */
    code?: string;
    page?: number & tags.Type<"int32">;
    limit?: number & tags.Type<"int32">;
  };

  /** PG사 신규 등록 DTO. 코드, 명칭, 엔드포인트 필수. */
  export type ICreate = {
    /** PG사명. */
    name: string;

    /** PG사 코드(유일값). */
    code: string;

    /** 연동용 API endpoint URI. */
    api_endpoint: string;
  };

  /** PG사 마스터 정보 부분/전체 수정용 DTO. 코드 등 일부 속성 불변. */
  export type IUpdate = {
    /** 명칭 수정. */
    name?: string;

    /** 엔드포인트URI수정. */
    api_endpoint?: string;
  };
}
