import { tags } from "typia";

/**
 * 외부 시스템과의 연동 이벤트 이력 레코드입니다.
 *
 * Prisma 스키마의 virtual_account_external_integration_logs 엔티티를 기반으로 하며,
 * ERP/쇼핑몰/금융 PG 등 각 연동 시점의 요청파라미터, 응답, 성공/실패, 오류 메시지, 시각정보 등 원자적 이벤트 정보를 기록합니다.
 * 규정상 3NF 준수 테이블로, 업무 시스템의 연동 모듈, 대시보드, 감사지원 등의 다양한 비즈니스 절차에 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountExternalIntegrationLogs = {
  /**
   * 외부 연동 이벤트 로그의 고유 식별자입니다.
   *
   * Prisma 스키마의 id 컬럼 설명과 동일하며, 각 연동 로그 이벤트를 유니크하게 식별합니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 연동 대상 외부 시스템 ID입니다.
   *
   * Prisma 스키마의 external_system_id 컬럼 설명을 참조하며, 어떤 외부 시스템(ERP, 쇼핑몰 등)과의 로그인지를
   * 명확히 식별합니다.
   */
  external_system_id: string & tags.Format<"uuid">;

  /**
   * 외부 연동 이벤트 유형(예: SYNC, PUSH, FAIL 등)을 나타냅니다.
   *
   * 이 필드는 Prisma 스키마 주석에 따라 로그 이벤트의 비즈니스 시나리오 분류를 지원합니다.
   */
  event_type: string;

  /**
   * 외부 시스템으로 전송된 원본 요청 데이터(예: JSON).
   *
   * Prisma 스키마의 설명에 따라 정규화된 개별 연동 요청을 기록합니다.
   */
  request_payload: string;

  /**
   * 외부 시스템에서 받은 응답 데이터(생략 가능).
   *
   * 실패 시에는 빈 값일 수 있으며, Prisma 스키마의 설명에서 'raw response'로 명시됩니다.
   */
  response_payload?: string | null;

  /**
   * 연동 이벤트 성공 여부를 명시하며, 관리자 알림 조건 및 재처리 정책과 연동됩니다.
   *
   * Prisma 스키마의 success 컬럼 설명을 기반으로 합니다.
   */
  success: boolean;

  /**
   * 실패 시 오류 메시지(Null 가능).
   *
   * Prisma 스키마의 설명에서의 'error message'를 반영합니다.
   */
  error_message?: string | null;

  /**
   * 이벤트 로그 생성 시각(ISO8601).
   *
   * 감사 및 시계열 분석을 위한 필드로 Prisma와 동일합니다.
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountExternalIntegrationLogs {
  /**
   * 외부 연동 로그 (virtual_account_external_integration_logs) 검색조건/페이징 DTO
   *
   * 외부 연동 이벤트 로그 검색과 대시보드 필터 연동에 사용.
   */
  export type IRequest = {
    /**
     * 외부 시스템의 UUID로 필터링(virtual_account_external_systems.id)
     *
     * 연동대상 필터
     */
    external_system_id?: string & tags.Format<"uuid">;

    /**
     * 이벤트 유형(SYNC, PUSH, FAIL 등)
     *
     * Virtual_account_external_integration_logs.event_type
     */
    event_type?: string;

    /** 성공/실패로 검색 */
    success?: boolean;
  };

  /**
   * 외부 연동 이벤트 로그 신규 생성요청 바디 타입입니다.
   *
   * ERP/쇼핑몰/API 시스템 등과의 통신에서 발생한 각 연동 시나리오별 원본 요청정보, 결과 상태, 생성시각, 오류정보 등
   * 실시간/비동기 이벤트를 원자적으로 입력할 때 사용하는 도메인 구조입니다.
   */
  export type ICreate = {
    /**
     * 연동 대상 외부 시스템 식별자입니다.
     *
     * Prisma 스키마의 external_system_id 컬럼 설명(외부 시스템 FK 참조)에서 재사용됩니다.
     */
    external_system_id: string & tags.Format<"uuid">;

    /**
     * 연동 이벤트 유형입니다(예: SYNC, PUSH, FAIL 등).
     *
     * 업무 목적에 따라 시스템 간 호출 종류를 구분하며, Prisma 원본 도메인 주석과 동일합니다.
     */
    event_type: string;

    /**
     * 외부 API 전송 또는 푸시를 위해 사용된 원본 요청 파라미터(대체로 JSON).
     *
     * Prisma 스키마에서 요구하는 원자적 RAW 요청을 직렬화/저장합니다.
     */
    request_payload: string;

    /**
     * 외부 시스템의 응답 데이터(Nullable).
     *
     * 실패 시 공란일 수 있으며, 로그 구축 표준에 따릅니다.
     */
    response_payload?: string | null;

    /**
     * 연동 성공 시 true, 실패 시 false.
     *
     * 관리자 대시보드/감사 정책과 연결되는 이진 필드입니다.
     */
    success: boolean;

    /**
     * 실패 시 오류 메시지(Null 가능).
     *
     * 자동화 실패, 수동처리 필요 등 다양한 케이스를 구분합니다.
     */
    error_message?: string | null;

    /**
     * 이벤트 생성 시각(ISO8601).
     *
     * Prisma의 created_at과 동일(로그 입력 시 서버시간으로 지정 권장).
     */
    created_at: string & tags.Format<"date-time">;
  };

  /**
   * 외부 연동 이벤트 로그 정보 수정용 바디 타입입니다.
   *
   * 이벤트 결과, 오류메시지, 응답 페이로드 등 단건 갱신 시 활용됩니다. 비즈니스 상 허용된 필드만 Patch 지원.
   */
  export type IUpdate = {
    /**
     * 이벤트 유형(예: SYNC, PUSH, FAIL). 수정이 필요할 경우 사용됩니다.
     *
     * Prisma 원본 주석 설명과 동일하며, business scenario에 따라 correction 용도로 활용합니다.
     */
    event_type?: string;

    /**
     * 외부 시스템 응답 RAW 페이로드(이벤트 후속 처리 시 갱신 용).
     *
     * 반드시 업데이트 필요할 때만 사용합니다.
     */
    response_payload?: string | null;

    /**
     * 연동 성공/실패 결과값.
     *
     * 업데이트 처리 시 실제 상태를 보정, 조정할 수 있도록 허용됩니다.
     */
    success?: boolean;

    /**
     * 실패/오류 사유(Nullable).
     *
     * 장애, API 실패, 수동관리 등 후처리 로그 보정용.
     */
    error_message?: string | null;
  };

  /**
   * 외부 연동 로그 삭제 결과 오브젝트입니다.
   *
   * 삭제 요청 결과(성공/실패 및 대상 식별)를 반환합니다.
   */
  export type IDeleteResult = {
    /**
     * 삭제(취소)된 외부 연동 로그의 고유 식별자.
     *
     * Prisma 스키마의 id 컬럼 설명과 일치합니다.
     */
    id: string & tags.Format<"uuid">;

    /**
     * 삭제 성공 여부. true=삭제됨, false=존재하지 않음 또는 삭제 실패.
     *
     * 삭제 성공/실패의 결과 플래그입니다.
     */
    deleted: boolean;
  };
}
