import { tags } from "typia";

/**
 * 관리자 정보 상세 오브젝트. 민감정보(비번해시)는 포함하지 않음. RBAC관리, 감사로그, 대시보드 주체 등에서 사용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountAdmin = {
  id: string & tags.Format<"uuid">;

  /** 로그인 계정명(고유). */
  username: string;

  /** 관리자 이메일(고유, 알림/리포트 전송에도 사용). */
  email: string;

  /** 등록일. */
  created_at: string & tags.Format<"date-time">;

  /** 마지막 로그인 시각. */
  last_login_at?: (string & tags.Format<"date-time">) | null;

  /** 계정 잠금 만료 일시. */
  locked_until?: (string & tags.Format<"date-time">) | null;
};
export namespace IVirtualAccountAdmin {
  /** 관리자 계정 리스트/검색 필터 DTO. 계정명, 이메일, 기간, 잠금여부, 페이징 포함. */
  export type IRequest = {
    /** 관리자 계정명(검색). */
    username?: string;

    /** 이메일(검색). */
    email?: string;

    /** 계정 생성일(조회 시작). */
    from_date?: string & tags.Format<"date-time">;

    /** 계정 생성일(조회 종료). */
    to_date?: string & tags.Format<"date-time">;

    /** Lockout/잠금 여부. */
    locked?: boolean;

    /** 페이지 번호. */
    page?: number & tags.Type<"int32">;

    /** 페이지당 수. */
    limit?: number & tags.Type<"int32">;
  };

  /** 관리자 계정 생성용 요청 DTO. 비번은 평문수신, 저장은 해시/암호화 적용. */
  export type ICreate = {
    /** 새 관리자 아이디(중복X). */
    username: string;

    /** 비밀번호(평문DTO). */
    password: string;

    /** 관리자 이메일(고유). */
    email: string;
  };

  /** 관리자 정보 일부 수정 요청 DTO. 패스워드 변경은 별도 엔드포인트 운영 권장. */
  export type IUpdate = {
    /** 관리자명 변경시. */
    username?: string;

    /** 이메일 변경. */
    email?: string;

    /** 잠금 해제/설정시. */
    locked_until?: (string & tags.Format<"date-time">) | null;
  };
}
