import { tags } from "typia";

/**
 * 가상계좌 시스템 보안 로그 단건
 *
 * Prisma 테이블 virtual_account_security_logs의 단일 엔트리를 대부분 그대로 반영합니다.
 *
 * 관리자/감사 대시보드, 이상탐지, Forensic 분석 등에 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountSecurityLog = {
  /**
   * 로그의 PK UUID입니다.
   *
   * Prisma DB의 primary key.
   *
   * 시스템/관리자/고객 등등 보안관련 이벤트 당 유일 식별자입니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 보안이벤트를 유발한 주체의 PK UUID.
   *
   * 고객, 관리자, 슈퍼관리자 또는 시스템 계정 등
   *
   * Prisma DB의 actor_id 컬럼 설명 참조.
   */
  actor_id: string & tags.Format<"uuid">;

  /**
   * 주체 종류(예: customer, admin, super_admin, system)
   *
   * Virtual_account_security_logs.actor_type
   *
   * 보안감사, 대시보드, 권한 정책에서 주체 분리 목적 설명 필요.
   */
  actor_type: string;

  /**
   * 이벤트 유형(예: login_fail, otp_fail, unauthorized_access 등)
   *
   * Virtual_account_security_logs.event_type 컬럼
   *
   * 보안 정책 및 장애 모니터링에서 사용.
   */
  event_type: string;

  /**
   * IP 주소(있을 경우). 접속/침해 탐지, 감사 기록 목적.
   *
   * Virtual_account_security_logs.ip
   */
  ip?: string | null;

  /**
   * 타겟 리소스 영역(account, oauth_client, hmac_key, notification, deposit 등)
   *
   * Virtual_account_security_logs.resource_type
   */
  resource_type: string;

  /**
   * 타겟 리소스 객체의 ID(존재 시). FK 또는 context key 값.
   *
   * Virtual_account_security_logs.resource_id
   */
  resource_id?: (string & tags.Format<"uuid">) | null;

  /**
   * 이벤트 세부(예: stacktrace, 에러 코드/메시지, 기타 Context)
   *
   * Virtual_account_security_logs.detail
   */
  detail?: string | null;

  /**
   * 이벤트 발생 시각(ISO8601)
   *
   * Virtual_account_security_logs.occurred_at
   */
  occurred_at: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountSecurityLog {
  /** 보안로그 리스트(시스템/관리자/고객별 행위 이벤트 등) 검색, 기간, 페이징 필터 DTO. 대시보드/포렌식 검색 등에 활용. */
  export type IRequest = {
    actor_id?: string & tags.Format<"uuid">;
    actor_type?: string;
    event_type?: string;
    resource_type?: string;
    resource_id?: string;
    from_date?: string & tags.Format<"date-time">;
    to_date?: string & tags.Format<"date-time">;
    page?: number & tags.Type<"int32">;
    limit?: number & tags.Type<"int32">;
  };

  /**
   * 보안 로그 생성 요청용 DTO
   *
   * 보안감사 및 이상 이벤트 발생시 사용합니다.
   *
   * Prisma 테이블 컬럼과 1:1 매핑하고, 비즈니스 입력 시 검증이 필요합니다.
   */
  export type ICreate = {
    /**
     * 보안이벤트를 유발한 주체(주로 관리자/시스템)의 UUID
     *
     * Prisma DB의 actor_id
     *
     * 로그남길때 반드시 지정.
     */
    actor_id: string & tags.Format<"uuid">;

    /**
     * 주체 종류(예: customer, admin, super_admin, system)
     *
     * 로그 남김의 주체 타입
     *
     * Virtual_account_security_logs.actor_type
     */
    actor_type: string;

    /**
     * 보안 이벤트 분류(예: login_fail, otp_fail, unauthorized_access 등)
     *
     * Virtual_account_security_logs.event_type
     */
    event_type: string;

    /**
     * 이벤트의 IP
     *
     * 로그 생성시 저장.
     *
     * 없을 경우 null.
     */
    ip?: string | null;

    /**
     * 타겟 리소스 유형(account, oauth_client, hmac_key 등)
     *
     * Virtual_account_security_logs.resource_type
     */
    resource_type: string;

    /**
     * 리소스 UUID(존재시)
     *
     * Virtual_account_security_logs.resource_id
     */
    resource_id?: (string & tags.Format<"uuid">) | null;

    /**
     * 상세 설명, 스택트레이스 등 개발/장애용 텍스트
     *
     * Virtual_account_security_logs.detail
     */
    detail?: string | null;

    /**
     * 발생 시각(납입 책임, 트래킹, 감사)
     *
     * Virtual_account_security_logs.occurred_at
     */
    occurred_at: string & tags.Format<"date-time">;
  };

  /**
   * 보안 로그 단건 수정용 DTO
   *
   * 주로 사후 forensic 분석, 장애 상황에서 수기 보정/상세작성시 사용합니다.
   */
  export type IUpdate = {
    /**
     * 이벤트 세부 정보/에러/스택트레이스의 수정
     *
     * Prisma DB의 detail 컬럼.
     *
     * 수정시만 사용하고 입력 생략 가능.
     */
    detail?: string | null;
  };
}
