import { tags } from "typia";

/**
 * 가상계좌 시스템의 고객 리스트/상세의 표준 반환 타입입니다. 이름, 연락처, 이메일, 등록일자, 삭제여부(soft delete) 정보만
 * 포함.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountCustomer = {
  /** 고객 고유 식별자. Prisma virtual_account_customers.id 컬럼 기준. */
  id: string & tags.Format<"uuid">;

  /** 고객명. 회원 실명 입력, 기본 KYC 요구조건. */
  name: string;

  /** 고객 연락처(핸드폰번호). 중복 없이 유일하도록 보장. 인증 및 알림 목적 필수. */
  phone: string;

  /** 고객 이메일. 중복 없음. 로그인, 알림, 비밀번호 재설정, 2FA 연계. */
  email: string;

  /** 고객 등록일시. ISO8601. 서비스 시작 시점 및 감사로그용. */
  registered_at: string & tags.Format<"date-time">;

  /** 삭제(탈퇴) 시각. 미삭제시 null. */
  deleted_at?: (string & tags.Format<"date-time">) | null;
};
export namespace IVirtualAccountCustomer {
  /**
   * 가상계좌 고객 목록 조회/검색/필터/페이징 조건 DTO. 이름, 연락처, 등록일 구간, 삭제 상태 등 다양한 조건으로 필터링하며,
   * 관리자 대시보드, 고객 관리, 엑셀 내보내기 등 복합 조건 API에 사용.
   */
  export type IRequest = {
    /** 고객명(검색어, 부분일치 필터, optional). 고객 리스트 및 대시보드 등에서 조건 검색할 때 사용. */
    name?: string;

    /** 고객 전화번호(검색, optional). */
    phone?: string;

    /** 이메일 주소(검색, optional). */
    email?: string;

    /** 등록일 검색 시작(ISO8601). */
    registered_from?: string & tags.Format<"date-time">;

    /** 등록일 검색 종료(ISO8601). */
    registered_to?: string & tags.Format<"date-time">;

    /** 삭제된 고객 포함 여부. true일 경우 소프트 삭제된 고객도 포함. */
    deleted?: boolean;

    /** 페이지 번호(1부터). 기본값은 1. */
    page?: number & tags.Type<"int32">;

    /** 페이지당 최대 건수. 기본값은 20 또는 환경설정. */
    limit?: number & tags.Type<"int32">;
  };

  /** 고객 신규 등록 시 입력데이터 DTO. 이름, 연락처, 이메일 필수. */
  export type ICreate = {
    /** 신규 고객명. 필수 입력. */
    name: string;

    /** 핸드폰/연락처(유일). */
    phone: string;

    /** 고객 이메일(유일). */
    email: string;
  };

  /** 고객 프로필(이름, 핸드폰, 이메일) 일부/전체 수정 요청 DTO. 등록일 등 변경 불가. */
  export type IUpdate = {
    /** 수정할 이름. 생략 시 기존 유지. */
    name?: string;

    /** 연락처 수정(중복불가 check). */
    phone?: string;

    /** 이메일 수정(중복불가 check). */
    email?: string;
  };
}
