import { tags } from "typia";

/**
 * 슈퍼관리자(최상위 관리자) 정보 오브젝트로, 시스템 설정/운영, 관리자 권한 관리 및 감사 정책 변경 등 전체 플랫폼 운영에 가장 높은
 * 권한을 갖는 계정 정보입니다.
 *
 * Prisma 스키마의 virtual_account_super_admins 테이블을 기준으로 정의되며, username(계정명),
 * created_at(생성시각) 등 핵심 식별정보만 포함하고 암호화된 비밀번호 등 민감정보는 절대 포함하지 않습니다.
 *
 * 관리자 등급 구분(일반/슈퍼) 구현, 감사로그 접근, 긴급정책 관리 등에 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountSuperAdmin = {
  /**
   * 슈퍼관리자 고유 식별자.
   *
   * Prisma 스키마 'virtual_account_super_admins.id' 컬럼에 해당하며, 시스템 내 슈퍼관리자를 고유하게
   * 식별합니다. UUID 포맷으로 제공되며, 모든 슈퍼관리자 엔티티의 기본 키입니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 로그인용 슈퍼관리자 계정명.
   *
   * Prisma 스키마 'virtual_account_super_admins.username' 컬럼에 해당하며, 루트 인증 목적으로
   * 필요한 사용자 이름이며, 반드시 시스템 내 유일값이어야 합니다.
   */
  username: string;

  /**
   * 계정 생성 시각을 나타내는 필드. 예시: '2025-06-01T13:00:00+09:00'.
   *
   * 감사로그, 계정 모니터링 및 시스템 정책/보안 관점에서 중요합니다.
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountSuperAdmin {
  /** 슈퍼관리자 리스트, 관리 필터/페이징 DTO. 계정명, 기간 등 filter. */
  export type IRequest = {
    /** 슈퍼관리자 계정명 필터. */
    username?: string;

    /** 등록(생성)일 기준 조회 시작. */
    from_date?: string & tags.Format<"date-time">;

    /** 등록(생성)일 기준 조회 종료. */
    to_date?: string & tags.Format<"date-time">;

    /** 페이지 번호. */
    page?: number & tags.Type<"int32">;

    /** 페이지당 행 수. */
    limit?: number & tags.Type<"int32">;
  };

  /**
   * 슈퍼관리자 신규 등록 요청 시 사용되는 DTO이며, username(계정명)과 비밀번호만을 입력받아, 생성 후 비밀번호는 즉시 해시
   * 처리되어 저장/활용됩니다.
   *
   * Prisma 스키마의 virtual_account_super_admins 테이블 생성 컨벤션과 일치하며, 관리자 추가/온보딩
   * 프로세스에서 사용됩니다.
   */
  export type ICreate = {
    /**
     * 등록할 슈퍼관리자 ID(계정명). 유일성과 포맷 규칙을 따라야 하며, Prisma 테이블에서 username에 매핑됩니다.
     *
     * 예시: 'supermaster2025'. 관리 및 감사 용도로 사용됨.
     */
    username: string;

    /**
     * 등록할 관리자 비밀번호(평문 수신, 저장은 해시 처리). 업무에서 입력시만 수집, 저장 시 반드시 해시화되어야 하며,
     * Prisma에는 password_hash 형태로 저장됨.
     */
    password: string;
  };

  /**
   * 슈퍼관리자 정보 수정(계정명, 비밀번호) 시 사용되는 DTO로, 변경 가능한 필드만 포함하며 모든 항목은 선택적으로 처리됩니다.
   *
   * Prisma 스키마의 virtual_account_super_admins 수정 정책에 준함.
   */
  export type IUpdate = {
    /** 관리자명(변경시). 유일성 검사가 동반됨. Prisma의 username 컬럼에 해당합니다. */
    username?: string;

    /** 비밀번호 수정용 필드(평문 전달, 저장은 해시화 처리). 비밀번호 변경 요청 시에만 입력합니다. */
    password?: string;
  };
}
