import { tags } from "typia";

/**
 * 가상계좌 RBAC 퍼미션(권한) 엔티티 오브젝트로, Prisma 'virtual_account_permissions' 테이블에 정의된 권한
 * 코드, 설명 등이 포함됩니다. RBAC 정책, 관리자 권한 화면 등에서 기준 정보로 사용.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountPermission = {
  /** 권한(퍼미션) 고유 식별자. Prisma 'virtual_account_permissions.id' 컬럼에 매핑. */
  id: string & tags.Format<"uuid">;

  /**
   * 퍼미션 코드명. RBAC 권한 관리에서 권리, 기능 명칭 및 접근 키. Prisma
   * 'virtual_account_permissions.code' 와 일치.
   */
  code: string;

  /** 퍼미션 상세 설명. 실제 권리의 업무적 의미, 제한 조건, 활용처 등. */
  description: string;
};
export namespace IVirtualAccountPermission {
  /**
   * RBAC 퍼미션(권한) 목록을 검색/필터/페이징할 때 사용하는 파라미터 오브젝트로, Prisma
   * virtual_account_permissions 테이블 검색에 연동됩니다.
   */
  export type IRequest = {
    /**
     * 퍼미션 코드(코드명) 필터링/검색에 사용. Prisma 'virtual_account_permissions.code' 컬럼
     * 활용.
     */
    code?: string;

    /** 페이지 넘버(페이징 쿼리용). 기본값 1. */
    page?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;

    /** 한 페이지당 데이터 건수. 기본값 100 또는 환경설정값 적용. */
    limit?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;
  };

  /**
   * 권한(RBAC Permission) 엔티티 생성용 요청 스키마입니다.
   *
   * Prisma 스키마의 virtual_account_permissions 테이블 구조와 컬럼 주석을 바탕으로, 신규 권한 코드와
   * 설명을 등록할 때 사용합니다. RBAC 체계의 세분화된 액션/권한 관리에 쓰이며, 코드 중복, 필수값 확인 등 유효성 정책을 반드시
   * 준수해야 합니다.
   */
  export type ICreate = {
    /**
     * 권한 코드. Prisma 스키마의 'code' 컬럼을 참조합니다.
     *
     * RBAC 체계에서 각 권한의 고유 식별자로 사용되며, 예시: 'VIEW_DASHBOARD'. 모든 권한 유형은 중복 없이
     * 최소 한 번 이상 할당되어야 하며, 시스템 정책 및 메뉴 접근 결정 기준이 됩니다.
     */
    code: string;

    /**
     * 권한 설명. Prisma 스키마 'description' 컬럼 주석 내용을 참고합니다.
     *
     * 비즈니스/기능적 용도를 자연어로 명시하며, 예시: '관리자 대시보드 접근 권한'. RBAC 매핑 및 관리자 화면 구성에서
     * 활용됩니다.
     */
    description: string;
  };

  /**
   * 권한(RBAC Permission) 수정 요청 스키마입니다.
   *
   * Virtual_account_permissions 테이블의 특정 권한 코드나 설명을 갱신할 때 사용합니다. 모든 변경은 히스토리에
   * 남겨야 하며, 비즈니스 및 보안 정책상 필수 필드는 없음(부분 수정 허용).
   */
  export type IUpdate = {
    /**
     * 권한 코드. Prisma 스키마의 'code' 컬럼을 참조합니다.
     *
     * 권한 코드의 변경(수정 시)에 사용되며, 중복될 수 없고 시스템 내 일관성 유지를 보장해야 합니다.
     */
    code?: string;

    /**
     * 권한 설명. Prisma 스키마의 'description' 컬럼 내용을 반영합니다.
     *
     * 권한의 비즈니스 목적과 실제 사용처를 상세하게 기술해야 합니다.
     */
    description?: string;
  };
}
