import { tags } from "typia";

/**
 * 가상계좌 알림 이벤트 단일 엔터티 구조입니다.
 *
 * 입금 안내, 오류, 만료, 관리자 경보 등이 이 엔터티로 관리됩니다.
 *
 * 각 필드는 Prisma DB virtual_account_notifications 테이블의 컬럼 구조 및 요구사항 문서 명세를 기반으로
 * 구성되어 있습니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountNotification = {
  /**
   * 알림 엔터티 고유 식별자
   *
   * Virtual_account_notifications.id PK
   */
  id: string & tags.Format<"uuid">;

  /** 알림 템플릿 ID (템플릿: virtual_account_notification_templates.id) */
  notification_template_id: string & tags.Format<"uuid">;

  /** 알림 채널 ID (채널: virtual_account_notification_channels.id) */
  notification_channel_id: string & tags.Format<"uuid">;

  /** 알림 이벤트 유형 (예: DEPOSIT_CONFIRMED, EXPIRED, ADMIN_ALERT 등) */
  event_type: string;

  /** 수신자(고객, 관리자, 슈퍼관리자 등) ID */
  recipient_id: string & tags.Format<"uuid">;

  /** 알림 발송 상태 코드(SENT, DELIVERED, FAILED 등) */
  status: string;

  /** 알림 생성(발송요청/트리거) 시각 */
  requested_at: string & tags.Format<"date-time">;

  /**
   * 알림이 발송된(시스템 채널에 전달한) 시각
   *
   * 일부 미전송/에러 시 null
   */
  sent_at?: string & tags.Format<"date-time">;

  /**
   * 최종 전달/수신이 완료된 시각(채널 전달확인 OK)
   *
   * 실패 시 null 허용
   */
  delivered_at?: string & tags.Format<"date-time">;
};
export namespace IVirtualAccountNotification {
  /** 알림 신규 등록용 DTO. 템플릿, 채널, 이벤트타입, 수신자 필수. 요청시각 미입력시 서버기준 자동. */
  export type ICreate = {
    notification_template_id: string & tags.Format<"uuid">;
    notification_channel_id: string & tags.Format<"uuid">;
    event_type: string;
    recipient_id: string & tags.Format<"uuid">;
    status: string;
    requested_at: string & tags.Format<"date-time">;
  };

  /** 알림 상태, 템플릿/채널/시각 등 일부 정보 변경용 DTO. allowed fields만 수정됨. */
  export type IUpdate = {
    status?: string;
    sent_at?: string & tags.Format<"date-time">;
    delivered_at?: string & tags.Format<"date-time">;
    notification_template_id?: string & tags.Format<"uuid">;
    notification_channel_id?: string & tags.Format<"uuid">;
  };

  /**
   * 알림 이력 목록 조회 시 요청하는 복합 쿼리 DTO입니다.
   *
   * 알림 이벤트 유형, 수신자, 채널, 상태, 기간, 페이징 등 복합 조건 검색/필터/정렬용 파라미터입니다.
   */
  export type IRequest = {
    /** 알림 이벤트 유형(필터링). 예: DEPOSIT_CONFIRMED, EXPIRED 등 */
    event_type?: string;

    /** 수신자(고객/관리자 등) 필터. */
    recipient_id?: string & tags.Format<"uuid">;

    /** 발송 채널(Kakao, Email 등) 필터. */
    notification_channel_id?: string & tags.Format<"uuid">;

    /** 알림 발송 상태(예: SENT, DELIVERED, FAILED 등) */
    status?: string;

    /** 알림 발생일/기간 검색(시작) */
    requested_from?: string & tags.Format<"date-time">;

    /** 알림 발생일/기간 검색(종료) */
    requested_to?: string & tags.Format<"date-time">;

    /** 조회 페이지 번호(페이징) */
    page?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;

    /** 페이지별 결과 크기 */
    limit?: number &
      tags.Type<"int32"> &
      tags.JsonSchemaPlugin<{
        format: "int32";
      }>;
  };
}
