import { tags } from "typia";

/**
 * 엑셀 내보내기(다운로드) 이력 단일 레코드 타입.
 *
 * `virtual_account_excel_exports` 테이블의 각 컬럼에 대한 설명 및 관리자, 데이터 종류, 요청 일시, 적용 필터,
 * 파일 경로, 성공/실패 여부 등의 정보를 포함합니다.
 *
 * 관리자 대시보드의 다운로드 이력 조회, 지원, 감사 목적 등으로 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountExcelExports = {
  /**
   * 엑셀 내보내기 로그의 고유 식별자(ID).
   *
   * Prisma: `id` (PK) 컬럼. 관리자가 개별적으로 수행한 내보내기 작업별 로그 ID.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 엑셀 내보내기 요청을 실행한 관리자 ID.
   *
   * Prisma: `virtual_account_admin_id` 컬럼. 내보내기 수행 주체 조회에 활용.
   */
  virtual_account_admin_id: string & tags.Format<"uuid">;

  /**
   * 다운로드한 데이터 종류 구분.
   *
   * Prisma: `export_type` 컬럼. 예: DEPOSIT_HISTORY, ACCOUNT_STATUS,
   * NOTIFICATIONS.
   */
  export_type: string;

  /**
   * 엑셀 내보내기 수행 시 적용된 필터 설정 값(JSON 직렬화).
   *
   * Prisma: `filter_applied` 컬럼. 다운로드 당시 검색조건, 필터, 기간, 상태 등이 모두 기록됩니다.
   */
  filter_applied: string;

  /**
   * 내보내기 요청 시각.
   *
   * Prisma: `requested_at` 컬럼. 작업의 생성 일시(타임스탬프) 기록.
   */
  requested_at: string & tags.Format<"date-time">;

  /**
   * 내보내기 작업의 성공/실패 여부.
   *
   * Prisma: `succeeded` 컬럼. true=성공, false=실패 기록.
   */
  succeeded: boolean;

  /**
   * 내보내기 파일(Excel)의 저장 위치(URI).
   *
   * Prisma: `file_path` 컬럼. S3 URI 등 또는 실패 시 null/미입력.
   */
  file_path?: string;
};
export namespace IVirtualAccountExcelExports {
  /**
   * 엑셀 내보내기 이력 검색 요청/필터 타입.
   *
   * 관리자별, 내보내기 유형별, 성공/실패 여부, 기간 등 다양한 필터링 조건으로 Excel 다운로드 로그 이력을 검색할 때
   * 사용합니다.
   */
  export type IRequest = {
    /**
     * 엑셀 내보내기 로그를 조회할 관리자의 ID.
     *
     * Prisma: `virtual_account_admin_id`. 관리자가 생성한 내역 만큼 필터링에 사용됩니다.
     */
    admin_id?: string & tags.Format<"uuid">;

    /**
     * 엑셀 내보내기 데이터 종류 구분 값.
     *
     * 예) DEPOSIT_HISTORY, ACCOUNT_STATUS, NOTIFICATIONS 등. Prisma:
     * `export_type`.
     */
    export_type?: string;

    /**
     * 다운로드 내역 검색 시작일(UTC/ISO8601).
     *
     * Prisma: `requested_at` 범위 필터로 이용.
     */
    requested_from?: string & tags.Format<"date-time">;

    /**
     * 다운로드 내역 검색 종료일(UTC/ISO8601).
     *
     * Prisma: `requested_at` 범위 필터로 이용.
     */
    requested_to?: string & tags.Format<"date-time">;

    /** 다운로드 성공/실패 여부로 필터링(true=성공, false=실패만) */
    succeeded?: boolean;
  };

  /**
   * 엑셀 내보내기 이력 신규 로그 생성 요청 타입.
   *
   * API에 의해 새로운 다운로드 기록을 추가할 때 사용. 필수 값은 수행 관리자, 내보내기 유형, 필터 정보이며, 성공시 파일 저장
   * 경로 포함.
   */
  export type ICreate = {
    /**
     * 내보내기 수행 관리자 ID.
     *
     * Prisma: `virtual_account_admin_id` 컬럼. 로그 생성 시 필수.
     */
    virtual_account_admin_id: string & tags.Format<"uuid">;

    /**
     * 다운로드하는 데이터 유형.
     *
     * Prisma: `export_type` 컬럼. 예: 'DEPOSIT_HISTORY', 'ACCOUNT_STATUS'.
     */
    export_type: string;

    /**
     * 다운로드 수행 시의 적용 필터 정보(JSON 직렬화).
     *
     * Prisma: `filter_applied` 컬럼. 다양한 조건 및 검색 파라미터 기록.
     */
    filter_applied: string;

    /**
     * 생성된 엑셀 파일의 저장 위치(URI).
     *
     * Prisma: `file_path` 컬럼. 성공시 경로 기록.
     */
    file_path?: string;
  };

  /**
   * 엑셀 내보내기 이력 갱신 요청 타입.
   *
   * 주로 파일의 실제 저장 위치 또는 성공여부(상태)만 추적시 사용. 설정가능한 값만 입력 가능.
   */
  export type IUpdate = {
    /**
     * 엑셀 파일 저장위치(URI) 갱신 값.
     *
     * 내보내기 완료 후 결과 경로를 업데이트할 때 주로 사용합니다.
     */
    file_path?: string;

    /**
     * 내보내기 성공/실패 여부 갱신 값.
     *
     * 배경 작업의 실패/성공 결과 반영시 활용.
     */
    succeeded?: boolean;
  };

  /**
   * 엑셀 내보내기 이력 삭제 결과 응답 타입.
   *
   * 삭제 성공여부와 상세 메시지를 전달합니다.
   */
  export type IDeleteResult = {
    /**
     * 삭제 성공 여부
     *
     * True: 삭제 성공, false: 대상 없음/이미 삭제됨
     */
    deleted: boolean;

    /**
     * 삭제 결과 상세 메시지
     *
     * 성공/실패 사유 등 기타 설명
     */
    message: string;
  };
}
