import { tags } from "typia";

/**
 * 알림 템플릿 단건 객체. 템플릿별 버전, 채널, 포맷, 활성여부 등 포함.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IVirtualAccountNotificationTemplate = {
  id?: string & tags.Format<"uuid">;
  template_code?: string;
  channel_type?: string;
  title?: string;
  body_format?: string;
  body_template?: string;
  language_code?: string;
  version?: number & tags.Type<"int32">;
  is_active?: boolean;
};
export namespace IVirtualAccountNotificationTemplate {
  /** 알림 템플릿 목록 검색/필터/페이징 DTO. */
  export type IRequest = {
    template_code?: string;
    channel_type?: string;
    title?: string;
    is_active?: boolean;
    language_code?: string;
    version?: number & tags.Type<"int32">;
  };

  /** 알림 템플릿 신규 등록 DTO. 버전 및 각 채널/언어별 템플릿 특성 표현 가능. */
  export type ICreate = {
    template_code: string;
    channel_type: string;
    title: string;
    body_format: string;
    body_template: string;
    language_code: string;
    version: number & tags.Type<"int32">;
    is_active: boolean;
  };

  /** 알림 템플릿 속성 중 일부만 패치/PATCH 수정할 때 사용하는 DTO. */
  export type IUpdate = {
    template_code?: string;
    channel_type?: string;
    title?: string;
    body_format?: string;
    body_template?: string;
    language_code?: string;
    version?: number & tags.Type<"int32">;
    is_active?: boolean;
  };
}
