import { IPage } from "./IPage";
import { virtual_account_IVirtualAccountNotificationTemplate } from "./virtual_account_IVirtualAccountNotificationTemplate";

/**
 * 알림 템플릿 목록 페이징/검색 응답에 사용되는 표준 페이징 컨테이너입니다.
 *
 * Prisma virtual_account_notification_templates 테이블 전체를 포함하며, 목록, 페이징, 통합 조회에
 * 주로 사용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IPageIVirtualAccountNotificationTemplate = {
  /** 페이지네이션 정보 객체. 페이징 및 전체 목록 길이, 현재 페이지 등 포함. */
  pagination: IPage.IPagination;

  /**
   * 실제 템플릿 목록 데이터.
   *
   * 요약 용도로도 활용 가능. 배열 항목은 각 템플릿 타입 준수.
   */
  data: virtual_account_IVirtualAccountNotificationTemplate[];
};
