import { tags } from "typia";

/**
 * 가상계좌 알림(virtual_account_notifications) 신규 등록 요청 body 스키마입니다.
 *
 * 알림 발송시 템플릿, 채널, 이벤트 유형, 수신자, 상태, 생성시간 등을 클라이언트에서 입력받아 생성합니다.
 *
 * Prisma 스키마 구조 및 업무 역할에 따라 엄격히 검증됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotification_ICreate = {
  /**
   * 알림 발송에 사용할 템플릿의 ID.
   *
   * Prisma 컬럼 참조, 발송 콘텐츠 형식 지정용.
   */
  notification_template_id: string & tags.Format<"uuid">;

  /**
   * 알림 발송에 사용할 채널의 ID (카카오톡, 이메일 등).
   *
   * Prisma 외래키 참조 관계.
   */
  notification_channel_id: string & tags.Format<"uuid">;

  /**
   * 알림 이벤트 유형(예: DEPOSIT_CONFIRMED, EXPIRED, ADMIN_ALERT 등).
   *
   * 업무/UX 요구에 따라 다양하게 확장.
   */
  event_type: string;

  /**
   * 알림을 받을 대상의 고유 ID(고객/관리자/슈퍼관리자 등).
   *
   * Prisma 테이블 recipient_id 컬럼. 타 엔터티와의 다양한 관계 지원.
   */
  recipient_id: string & tags.Format<"uuid">;

  /**
   * 초기 알림 상태값(SENT, PENDING 등 지정).
   *
   * 알림 제어 및 이력 관리 용도.
   */
  status: string;

  /**
   * 알림이 생성/요청된 시각(ISO8601).
   *
   * 감사로그 및 통계, 이중 처리 방지 등 사용.
   */
  requested_at: string & tags.Format<"date-time">;
};
