import { tags } from "typia";

/**
 * 대시보드/리포트 지표의 스냅샷 레코드 엔터티입니다. virtual_account_materialized_stats 테이블의 1개 row를
 * 그대로 구조화해 정의하였으며, 관리자 대시보드, 보고서, 통계분석, 성능 튜닝용 리포팅에 주로 사용됩니다.
 *
 * 각 프로퍼티는 스키마 기술 주석을 참고하여 배열되었고, 데이터 웨어하우스/ETL/정기수집 등 다양한 대용량 대시보드 집계 업무용으로
 * 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_materialized_stats = {
  /** 각 대시보드/리포트용 집계 스냅샷의 유일 식별자. */
  id: string & tags.Format<"uuid">;

  /** 수집된 지표의 논리적 키(예: 'active_accounts', 'fail_deposit_count' 등). */
  stat_key: string;

  /** 지표의 스냅샷 값(문자열). 다양한 유형 집계값 저장 가능. */
  stat_value: string;

  /** 해당 값 스냅샷의 생성 시각. ETL/BATCH로 수집된 기준시각. */
  as_of: string & tags.Format<"date-time">;
};
export namespace virtual_account_materialized_stats {
  /**
   * 신규 대시보드/리포트용 집계값 스냅샷 레코드 생성 요청 타입입니다. 관리자 대시보드 ETL, 자동리포트, 매트릭스 통계 신규 집계
   * 수집 등 모든 신규 스냅샷 생성에 공용으로 사용합니다.
   */
  export type ICreate = {
    /** 신규 집계 지표의 논리키. unique하지 않을 수 있으나, as_of와 조합하여 식별 목적. */
    stat_key: string;

    /** 수집된 대시보드/분석/성능 지표의 값. 자유형 문자열로 보관(예: 집계수, 평균, % 등). */
    stat_value: string;

    /** 본 값이 수집/스냅샷된 시점을 기록합니다. ETL/BATCH 시각 등 기준. */
    as_of: string & tags.Format<"date-time">;
  };

  /**
   * 대시보드용 집계값 스냅샷 레코드(virtual_account_materialized_stats) 업데이트 요청입니다.
   * 지표키/값/스냅샷시점을 갱신하거나정정할 때 사용합니다.
   */
  export type IUpdate = {
    /** 수정 대상 지표의 논리키. */
    stat_key?: string;

    /** 수정/갱신할 집계값. 문자열. */
    stat_value?: string;

    /** 수정할 스냅샷 시점. */
    as_of?: string & tags.Format<"date-time">;
  };

  /** 대시보드 집계값 스냅샷 삭제 결과 리스폰스 타입입니다. 관리 UI, 자동 클린업, 감사 추적 등에서 상태 확인 목적으로 사용합니다. */
  export type IDeleteResponse = {
    /** 삭제가 정상 수행되었는지 여부. 성공시 true, 실패/불가시 false. */
    success: boolean;

    /** 삭제된 집계 레코드의 식별자. */
    deleted_id: string & tags.Format<"uuid">;

    /** 삭제 사유, 불가 사유, 시스템 오류 등 상세 메시지. */
    extra_message?: string;
  };
}
