import { tags } from "typia";

/**
 * 가상계좌 알림(virtual_account_notifications) 수정 요청에 사용하는 body 타입입니다.
 *
 * 알림의 상태(status), 발송/도달 시각, 템플릿/채널 재설정 등 다양한 알림 운영 시에 적용합니다.
 *
 * Prisma 테이블 구조 및 요구사항 기반, mutable 컬럼만 포함.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotification_IUpdate = {
  /**
   * 알림의 상태값(SENT, DELIVERED, FAILED 등) 수정용.
   *
   * 상태 변경에 따라 이력/Audit 로그 생성됨.
   */
  status?: string;

  /**
   * 새 알림 발송 시각 값. null 가능.
   *
   * 상태에 따라 업데이트 가능.
   */
  sent_at?: (string & tags.Format<"date-time">) | null;

  /**
   * 알림 도달 완료(수신확정) 시각. null 가능.
   *
   * 공지 상태나 실패 케이스에 따라 의미가 달라짐.
   */
  delivered_at?: (string & tags.Format<"date-time">) | null;

  /**
   * 템플릿 변경(수동 재발송 등) 시 새 템플릿 ID로 갱신.
   *
   * 업무상 필요시만 입력.
   */
  notification_template_id?: string & tags.Format<"uuid">;

  /**
   * 발송 채널 변경이 필요한 경우(예, 카카오톡→E-mail)만 입력.
   *
   * 업무상 필요시에만 입력.
   */
  notification_channel_id?: string & tags.Format<"uuid">;
};
