import { tags } from "typia";

/**
 * 알림 템플릿 리스트/검색/PATCH API의 요청 body 타입입니다.
 *
 * 템플릿코드, 채널타입, 제목, 사용여부, 언어, 버전 등 조건별 검색/필터 및 페이징 시 사용합니다.
 *
 * 모든 필드는 옵션이며, 다양한 조합 지원을 목표로 합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotificationTemplate_IRequest = {
  /**
   * 템플릿의 논리적 코드(예: 'DEPOSIT_CONFIRMED_KAKAO').
   *
   * 검색/필터에 사용. DB 고유키 아님.
   */
  template_code?: string;

  /**
   * 채널 구분(예: 카카오, email, sms 등).
   *
   * 템플릿/채널 전체 목록에서 필터링용.
   */
  channel_type?: string;

  /**
   * 템플릿 제목(메일제목, SMS Subject 등).
   *
   * 검색용.
   */
  title?: string;

  /** 활성화 여부로만 필터링하고자 할 때. */
  is_active?: boolean;

  /**
   * 템플릿 언어 구분(예: 'ko').
   *
   * 다국어 지원/필터용.
   */
  language_code?: string;

  /**
   * 템플릿 버전 넘버 기준으로 검색할 때.
   *
   * 테이블 버전가시화 용.
   */
  version?: number & tags.Type<"int32">;
};
