import { tags } from "typia";

/**
 * 알림 채널 엔터티(virtual_account_notification_channels) 메인 스키마.
 *
 * 카카오, 메일, SMS, 친구톡 등 여러 발송채널을 시스템적으로 관리하며,
 *
 * DB 컬럼/비즈니스 정책/보안 요구조건을 모두 준수합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotificationChannel = {
  /**
   * 알림 채널 아이디(PK UUID).
   *
   * Virtual_account_notification_channels 테이블과 매핑됨.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 채널 타입(카카오, email, sms 등 구분 string).
   *
   * Channel별 구분, 중복금지.
   */
  channel_type: string;

  /**
   * 채널의 관리자 UI/설정 표시명.
   *
   * UX상 표기, 검색 등 활용.
   */
  display_name: string;

  /**
   * 채널 사용 가능여부.
   *
   * 관리자는 off 처리로 발송 차단 가능.
   */
  is_active: boolean;

  /**
   * 연동용 API 키, config 등 JSON 직렬화.
   *
   * 실제 송신/설정 로딩 등에서 활용(보안항목).
   */
  settings_json: string;
};
