import { tags } from "typia";

/**
 * 가상계좌 알림 메인 엔터티입니다.
 *
 * Prisma DB의 'virtual_account_notifications' 테이블에 대응되는 유형으로, 입금, 오류, 만료, 관리자 경보
 * 등 시스템 내 모든 알림 이벤트를 원자적으로 기록합니다.
 *
 * 각 행은 템플릿, 채널, 수신자, 상태, 트리거 유형, 발송 및 도달 시간 등 업무 및 컴플라이언스 요구사항을 완결적으로 반영합니다.
 *
 * 이 타입은 다양한 트리거 이벤트와 멀티채널 발송 조건, 시스템 감사 추적, 이력/통계, 발송 관리에 핵심적으로 활용됩니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotification = {
  /**
   * 알림 이벤트의 고유 식별자입니다.
   *
   * Prisma 스키마 'virtual_account_notifications' 테이블의 기본키. 시스템 내 개별 알림 이벤트를
   * 식별합니다.
   */
  id: string & tags.Format<"uuid">;

  /**
   * 알림에 사용된 템플릿의 ID입니다.
   *
   * Prisma 스키마 컬럼 참조: 어떤 템플릿을 이용해 발송되었는지 추적합니다.
   */
  notification_template_id: string & tags.Format<"uuid">;

  /**
   * 사용된 알림 채널(KakaoTalk, 이메일 등)의 ID입니다.
   *
   * Prisma 스키마에서 채널 테이블과 1:N 관계 지정.
   */
  notification_channel_id: string & tags.Format<"uuid">;

  /**
   * 알림의 트리거 유형(예: DEPOSIT_CONFIRMED, EXPIRED, ADMIN_ALERT 등).
   *
   * 업무 요건별 다양한 상황의 구분 용도.
   */
  event_type: string;

  /**
   * 알림을 수신하는 주체(고객, 관리자, 슈퍼관리자)의 고유 PK입니다.
   *
   * Prisma 스키마 설명에 따라 다양한 대상에게 전달되는 경우에 사용.
   */
  recipient_id: string & tags.Format<"uuid">;

  /**
   * 알림의 현재 발송 상태(SENT, DELIVERED, FAILED 등).
   *
   * 알림 이력 관리 및 재처리/통계 분석 용.
   */
  status: string;

  /**
   * 이 알림이 생성된 시각 (ISO8601).
   *
   * 요구사항상 이벤트, 알림 타임라인, 감사로그 등에서 사용.
   */
  requested_at: string & tags.Format<"date-time">;

  /**
   * 시스템에서 채널로 실제 전송된 시각 (null 허용).
   *
   * 실제 발송 시간 기록용.
   */
  sent_at?: (string & tags.Format<"date-time">) | null;

  /**
   * 최종 채널에서 전달 완료된 시각(예: 카카오로 수신됨 등, null 허용).
   *
   * 알림 성공/실패 분석 및 감사 이력 작성 시 필요.
   */
  delivered_at?: (string & tags.Format<"date-time">) | null;
};
