import { tags } from "typia";

/**
 * 알림 템플릿 엔터티(virtual_account_notification_templates) 모델입니다.
 *
 * 각종 알림에서 포맷/이벤트별 메시지 구조를 제공하며, 다국어/채널별 가변규격까지 완전히 커버함.
 *
 * Prisma 테이블 스키마의 각 컬럼별 주석을 충실히 반영하여, 실제 시스템의 템플릿 관리, 이력관리, 활성화 정책, 채널별 확장 니즈를
 * 모두 포함합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IVirtualAccountNotificationTemplate = {
  /**
   * 알림 템플릿의 고유키(PK UUID).
   *
   * Virtual_account_notification_templates의 ID 컬럼과 매핑.
   */
  id: string & tags.Format<"uuid">;

  /** 논리적 템플릿 코드. 채널/타입별 소스 구분에 주로 사용. */
  template_code: string;

  /**
   * 알림 채널 구분: kakao / email / sms 등.
   *
   * Template/channel 관계의 참조 컬럼.
   */
  channel_type: string;

  /**
   * 템플릿 제목(예: '입금확인 안내').
   *
   * 메일제목/SMS 제목 등.
   */
  title: string;

  /**
   * 본문 형식(text/html/markdown).
   *
   * 채널특성별 파싱방식 - 업무확장성 고려.
   */
  body_format: string;

  /**
   * 템플릿 메시지 본문 (치환변수포함).
   *
   * 템플릿 기반의 dynamic 렌더링 구조용.
   */
  body_template: string;

  /**
   * 언어구분(예: 'ko', 'en').
   *
   * 다국어 템플릿 지원.
   */
  language_code: string;

  /**
   * 템플릿 버전 번호(업데이트 이력용).
   *
   * 템플릿 변경관리/audit용.
   */
  version: number & tags.Type<"int32">;

  /** 활성여부. 비활성시 신규 알림에서 제외. */
  is_active: boolean;
};
