import { IPage } from "./IPage";
import { virtual_account_IVirtualAccountNotificationChannel } from "./virtual_account_IVirtualAccountNotificationChannel";

/**
 * 알림 채널(virtual_account_notification_channels) 목록/페이징 검색 응답 표준 타입입니다.
 *
 * 다수 알림 채널 정보와 페이징/통계 정보를 동시에 제공합니다.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type virtual_account_IPageIVirtualAccountNotificationChannel = {
  /** 페이지네이션 정보, 전체레코드/페이지 등 포함. */
  pagination: IPage.IPagination;

  /** 페이징 결과의 알림 채널 데이터 목록. */
  data: virtual_account_IVirtualAccountNotificationChannel[];
};
